// build.mjs — generate ui/compare.html from the canonical engine + data.
//
// Why: the Compare view must run the SAME corrected-time engine the acceptance tests
// verify — never a hand-maintained copy that can silently drift. This inlines
// ../src/ratings.mjs + ../src/engine.mjs + ../data/boats.json into ui/template.html
// so compare.html is a single self-contained file that is nonetheless generated from
// (and provably identical to) the audited source.
//
// Run:  node ui/build.mjs      (from phase0-engine/)   → writes ui/compare.html

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const read = (p) => readFileSync(join(root, p), 'utf8');

// Strip module syntax so the two files can live as plain top-level declarations
// inside one <script type="module">. We remove `export ` prefixes, the relative
// import of ratings, and the re-export footer. No logic is altered.
function stripModule(src) {
  return src
    .replace(/^\s*import\s+\{[^}]*\}\s+from\s+['"]\.\/ratings\.mjs['"];\s*$/m, '')
    .replace(/^\s*export\s+\{[^}]*\};\s*$/mg, '')
    .replace(/^export\s+/mg, '');
}

const ratings  = stripModule(read('src/ratings.mjs'));
const engine   = stripModule(read('src/engine.mjs'));
const courseIo = stripModule(read('src/course-io.mjs'));
const engineBlock =
  `/* ---- inlined from src/ratings.mjs ---- */\n${ratings}\n` +
  `/* ---- inlined from src/engine.mjs ---- */\n${engine}\n` +
  `/* ---- inlined from src/course-io.mjs ---- */\n${courseIo}`;

const data = read('data/boats.json').trim();
const dataBlock = `/* ---- inlined from data/boats.json ---- */\nconst DATA = ${data};`;

let out = read('ui/template.html')
  .replace('//__ENGINE__//', () => engineBlock)
  .replace('//__DATA__//', () => dataBlock);

if (out.includes('//__ENGINE__//') || out.includes('//__DATA__//')) {
  throw new Error('build: a placeholder was not replaced — check ui/template.html markers.');
}

const banner = `<!-- GENERATED by ui/build.mjs on ${new Date().toISOString().slice(0,10)} — DO NOT EDIT.\n     Edit ui/template.html + src/*.mjs + data/boats.json, then: node ui/build.mjs -->\n`;
out = out.replace(/^<!DOCTYPE html>\n/, `<!DOCTYPE html>\n${banner}`);

writeFileSync(join(root, 'ui/compare.html'), out);
console.log(`ui/compare.html written (${out.length} bytes) — engine + data inlined from src/.`);
